sonar.projectKey=bytebattle-judge-worker
sonar.projectName=ByteBattle Judge Worker
sonar.projectVersion=0.0.1

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/sandbox/**,**/coverage/**,**/*.spec.ts,**/*.test.ts
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.sonar.json
sonar.sourceEncoding=UTF-8
sonar.coverage.inclusions=src/judge/judge.processor.ts
sonar.coverage.exclusions=**/*.module.ts,**/*.dto.ts,**/*.types.ts,**/*.constants.ts,**/*.enum.ts,**/*.decorator.ts,**/*.interface.ts,**/*.d.ts,**/main.ts,**/app.module.ts,**/index.ts
