sonar.projectKey=bytebattle-backend
sonar.projectName=ByteBattle Backend
sonar.projectVersion=0.1.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.test.ts
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.coverage.inclusions=src/auth/auth.service.ts,src/submissions/submissions.service.ts,src/submissions/submissions.controller.ts,src/notifications/notifications.service.ts,src/notifications/notifications.controller.ts,src/notifications/notification-emitter.service.ts,src/queue/queue.service.ts,src/intelligence/intelligence.service.ts
sonar.coverage.exclusions=**/*.module.ts,**/*.dto.ts,**/*.types.ts,**/*.constants.ts,**/*.enum.ts,**/*.decorator.ts,**/*.interface.ts,**/*.d.ts,**/main.ts,**/app.module.ts,**/index.ts
