import { DomainPromptConfig } from './base';

export const backendEngineeringPrompt: DomainPromptConfig = {
    domain: 'Backend Engineering',
    domainEnum: 'BACKEND_ENGINEERING',
    persona: {
        en: 'You are a Staff Backend Engineer at a high-scale tech company with 10+ years building distributed systems. You have architected APIs serving billions of requests daily and have deep expertise in databases, message queues, and system design. You value reliability, observability, and pragmatic architecture decisions.',
        fr: 'Vous êtes un Ingénieur Backend Staff dans une entreprise tech de grande envergure avec plus de 10 ans d\'expérience dans la construction de systèmes distribués. Vous avez conçu des API servant des milliards de requêtes par jour et possédez une expertise approfondie en bases de données, files de messages et conception de systèmes. Vous valorisez la fiabilité, l\'observabilité et les décisions architecturales pragmatiques.',
    },
    subTopics: [
        'RESTful APIs',
        'GraphQL',
        'gRPC',
        'Database Design',
        'Caching',
        'Message Queues',
        'Authentication/JWT',
        'Microservices',
        'API Versioning',
        'Rate Limiting',
        'Logging/Monitoring',
        'Database Scaling',
    ],
    questionsByLevel: {
        easy: [
            'What is the difference between SQL and NoSQL databases?',
            'Explain RESTful API design principles.',
            'What is a microservice architecture?',
            'How does database indexing work?',
            'What is the purpose of caching?',
            'Explain the ACID properties of transactions.',
            'What is the difference between PUT and PATCH?',
            'How do you handle errors in API design?',
        ],
        medium: [
            'Design a RESTful API for a todo application.',
            'How would you implement authentication without storing passwords?',
            'Design a database schema for a multi-tenant SaaS application.',
            'Explain how you would implement a distributed caching strategy.',
            'How would you handle database migrations in production?',
            'Design an event-driven architecture for order processing.',
            'Explain how you would implement API rate limiting.',
            'How would you design a notification system with multiple channels?',
        ],
        hard: [
            'Design a real-time chat system supporting millions of concurrent connections.',
            'Explain how you would build a distributed transactions system.',
            'Design an API gateway architecture for microservices.',
            'How would you implement a CQRS pattern for a high-throughput system?',
            'Design a database sharding strategy for petabyte-scale data.',
            'Explain how you would build an event sourcing system.',
            'Design a search engine backend handling millions of queries.',
            'How would you architect a system for processing payments with idempotency?',
        ],
    },
    evaluationCriteria: [
        'API Design',
        'Database Knowledge',
        'System Design',
        'Scalability',
        'Reliability',
        'Observability',
    ],
    scoringGuidelines: 'Evaluate based on API design skills, database expertise, ability to design for scale and reliability, understanding of trade-offs, and practical experience with distributed systems.',
};
