import { DomainPromptConfig } from './base';

export const cloudComputingPrompt: DomainPromptConfig = {
    domain: 'Cloud Computing',
    domainEnum: 'CLOUD_COMPUTING',
    persona: {
        en: 'You are a Senior Cloud Architect at a major cloud provider (AWS, Azure, or GCP) with 10+ years of experience. You specialize in designing scalable, fault-tolerant distributed systems and have helped dozens of enterprises migrate to the cloud. You value practical solutions backed by real-world experience.',
        fr: 'Vous êtes un Architecte Cloud Senior chez un fournisseur cloud majeur (AWS, Azure ou GCP) avec plus de 10 ans d\'expérience. Vous vous spécialisez dans la conception de systèmes distribués évolutifs et tolérants aux pannes et avez aidé des dizaines d\'entreprises à migrer vers le cloud. Vous valorisez les solutions pratiques étayées par une expérience concrète.',
    },
    subTopics: [
        'EC2/ECS/EKS',
        'Lambda/Cloud Functions',
        'S3/Blob Storage',
        'VPC/Networking',
        'IAM/Roles/Policies',
        'Auto-scaling',
        'Load Balancing',
        'CDN/CloudFront',
        'Serverless Architecture',
        'Cloud Security',
        'Cost Optimization',
        'Multi-cloud Strategies',
    ],
    questionsByLevel: {
        easy: [
            'What is the difference between a public and private subnet in a VPC?',
            'Explain the basic concept of auto-scaling groups.',
            'What are the main storage types available in cloud computing?',
            'How does a load balancer improve application performance?',
            'What is the purpose of IAM roles in AWS?',
            'Explain the difference between S3 Standard and S3 Glacier.',
            'What is a VPC and why would you use one?',
            'How do you secure data at rest in the cloud?',
        ],
        medium: [
            'Design a highly available architecture for a web application with 99.99% uptime.',
            'Explain how you would implement a disaster recovery strategy for a cloud-hosted application.',
            'How would you optimize costs for a frequently accessed application with variable traffic patterns?',
            'Design a serverless architecture for processing uploaded images.',
            'Explain the trade-offs between microservices and monolithic architecture in the cloud.',
            'How would you implement a multi-region active-active deployment?',
            'Design a secure CI/CD pipeline that deploys to the cloud.',
            'Explain how you would handle secrets management in a cloud environment.',
        ],
        hard: [
            'Design a global-scale distributed system that handles millions of requests per second.',
            'Explain how you would architect a zero-downtime migration from on-premise to the cloud.',
            'Design a chaos engineering strategy for a cloud-native microservices application.',
            'How would you implement a multi-cloud strategy while minimizing vendor lock-in?',
            'Design a real-time analytics pipeline processing petabytes of data per day.',
            'Explain how you would implement a defense-in-depth security strategy for a cloud environment.',
            'Design a cost-effective data lake architecture with proper governance.',
            'How would you architect a system that needs to handle 99.999% availability with geographic distribution?',
        ],
    },
    evaluationCriteria: [
        'System Design Skills',
        'Cloud Service Knowledge',
        'Scalability Understanding',
        'Security Best Practices',
        'Cost Awareness',
        'Practical Experience',
    ],
    scoringGuidelines: 'Score based on depth of understanding (not just definitions), ability to discuss trade-offs, awareness of real-world constraints, and practical implementation considerations.',
};
