import { DomainPromptConfig } from "./base";

export const cybersecurityPrompt: DomainPromptConfig = {
  domain: "Cybersecurity",
  domainEnum: "CYBERSECURITY",
  persona: {
    en: "You are a Chief Security Officer at a Fortune 500 company with 15+ years of experience in information security. You hold CISSP, CISM, and CEH certifications. You have led incident response teams during major security breaches and have implemented security programs that have protected millions of users. You are methodical, risk-aware, and believe security is everyone's responsibility.",
    fr: "Vous êtes un Directeur de la Sécurité de l'Information (RSSI) dans une entreprise du Fortune 500 avec plus de 15 ans d'expérience en sécurité de l'information. Vous détenez les certifications CISSP, CISM et CEH. Vous avez dirigé des équipes de réponse aux incidents lors de violations de sécurité majeures et avez mis en place des programmes de sécurité protégeant des millions d'utilisateurs. Vous êtes méthodique, conscient des risques et pensez que la sécurité est la responsabilité de tous.",
  },
  subTopics: [
    "OWASP Top 10",
    "Authentication/Authorization",
    "Encryption",
    "Network Security",
    "Penetration Testing",
    "Incident Response",
    "Compliance (GDPR, SOC2)",
    "Threat Modeling",
    "Secure Coding",
    "Vulnerability Assessment",
    "SIEM/SOAR",
    "Zero Trust Architecture",
  ],
  questionsByLevel: {
    easy: [
      "What is the difference between authentication and authorization?",
      "Explain what HTTPS does and why it's important.",
      "What is SQL injection and how do you prevent it?",
      "What are the OWASP Top 10 vulnerabilities?",
      "How do you securely store passwords?",
      "What is XSS and how do you mitigate it?",
      "Explain the principle of least privilege.",
      "What is a CSRF attack?",
    ],
    medium: [
      "Design a secure authentication system for a web application.",
      "How would you implement a bug bounty program?",
      "Explain your approach to security code review.",
      "Design an incident response plan for a data breach.",
      "How would you implement multi-factor authentication?",
      "Explain how you would conduct a security audit.",
      "Design a secrets management strategy for microservices.",
      "How would you handle a zero-day vulnerability disclosure?",
    ],
    hard: [
      "Design a zero-trust architecture for a complex enterprise network.",
      "Explain how you would architect a security operations center.",
      "Design a threat modeling process for a new product.",
      "How would you implement security champions across engineering teams?",
      "Design a SIEM integration strategy for multi-cloud environments.",
      "Explain how you would build a security awareness training program.",
      "Design a red team/blue team exercise framework.",
      "How would you architect for compliance with GDPR and SOC2 simultaneously?",
    ],
  },
  evaluationCriteria: [
    "Security Fundamentals",
    "Threat Awareness",
    "Risk Assessment",
    "Incident Response",
    "Secure Design",
    "Compliance Knowledge",
  ],
  scoringGuidelines:
    "Evaluate based on depth of security knowledge, understanding of attack vectors, practical mitigation strategies, and awareness of both technical and organizational security aspects.",
};
