import { DomainPromptConfig } from "./base";

export const dataScienceAIPrompt: DomainPromptConfig = {
  domain: "Data Science & AI",
  domainEnum: "DATA_SCIENCE_AI",
  persona: {
    en: "You are a Lead Data Scientist at a leading AI research lab with a PhD in Machine Learning from Stanford. You have published 30+ papers in top-tier conferences and have deployed ML models serving millions of users. You balance academic rigor with practical business impact and believe in responsible AI development.",
    fr: "Vous êtes un Lead Data Scientist dans un laboratoire de recherche en IA de premier plan avec un PhD en Apprentissage Automatique de Stanford. Vous avez publié plus de 30 articles dans des conférences de premier plan et avez déployé des modèles ML servant des millions d'utilisateurs. Vous conciliez rigueur académique et impact commercial pratique et croyez en un développement responsable de l'IA.",
  },
  subTopics: [
    "Machine Learning Algorithms",
    "Deep Learning",
    "Natural Language Processing",
    "Computer Vision",
    "MLOps",
    "Feature Engineering",
    "Model Evaluation",
    "A/B Testing",
    "Data Engineering",
    "Statistics",
    "Responsible AI",
    "ML System Design",
  ],
  questionsByLevel: {
    easy: [
      "What is the difference between supervised and unsupervised learning?",
      "Explain overfitting and how to prevent it.",
      "What is gradient descent?",
      "How do you handle missing data in a dataset?",
      "What is the purpose of cross-validation?",
      "Explain the bias-variance tradeoff.",
      "What is regularization and when would you use it?",
      "How do you evaluate a classification model?",
    ],
    medium: [
      "Design a recommendation system for an e-commerce platform.",
      "How would you build a churn prediction model for a subscription service?",
      "Design a feature engineering pipeline for NLP tasks.",
      "Explain how you would implement A/B testing for an ML model.",
      "How would you handle imbalanced datasets?",
      "Design a model monitoring system for production ML models.",
      "Explain how you would approach model explainability.",
      "How would you build an end-to-end ML pipeline?",
    ],
    hard: [
      "Design a real-time fraud detection system with latency constraints.",
      "Explain how you would build a large language model fine-tuning pipeline.",
      "Design a multi-task learning system for complex predictions.",
      "How would you architect a vector database for semantic search at scale?",
      "Design a responsible AI framework for hiring decisions.",
      "Explain how you would build a reinforcement learning system for dynamic pricing.",
      "Design a computer vision system for real-time object detection in video streams.",
      "How would you build a federated learning system that preserves privacy?",
    ],
  },
  evaluationCriteria: [
    "ML Fundamentals",
    "Algorithm Selection",
    "Data Handling",
    "Model Evaluation",
    "Production Readiness",
    "Business Impact",
  ],
  scoringGuidelines:
    "Evaluate based on understanding of ML fundamentals, ability to select appropriate approaches, practical considerations for production systems, and awareness of ethical implications.",
};
