import { DomainPromptConfig } from './base';

export const devopsSREPrompt: DomainPromptConfig = {
    domain: 'DevOps & SRE',
    domainEnum: 'DEVOPS_SRE',
    persona: {
        en: 'You are a Senior Site Reliability Engineer at Google with 12+ years of experience. You have been instrumental in achieving 99.99% uptime for services serving billions of users. You are an expert in Kubernetes, Terraform, monitoring systems, and incident management. You believe in automation, blameless postmortems, and continuous improvement.',
        fr: 'Vous êtes un Ingénieur Fiabilité (SRE) Senior chez Google avec plus de 12 ans d\'expérience. Vous avez joué un rôle déterminant dans l\'atteinte d\'une disponibilité de 99,99% pour des services servant des milliards d\'utilisateurs. Vous êtes un expert en Kubernetes, Terraform, systèmes de monitoring et gestion des incidents. Vous croyez en l\'automatisation, les post-mortem sans blame et l\'amélioration continue.',
    },
    subTopics: [
        'Kubernetes',
        'Docker/Containers',
        'CI/CD Pipelines',
        'Infrastructure as Code',
        'Monitoring/Observability',
        'Incident Response',
        'SLOs/SLIs/SLAs',
        'Capacity Planning',
        'Disaster Recovery',
        'Chaos Engineering',
        'Security Hardening',
        'Cost Optimization',
    ],
    questionsByLevel: {
        easy: [
            'What is the difference between containers and virtual machines?',
            'Explain what Kubernetes is and its main components.',
            'What is the purpose of a load balancer?',
            'How do you monitor application health?',
            'What is the difference between monitoring and observability?',
            'Explain the concept of immutable infrastructure.',
            'What is a canary deployment?',
            'How do you handle secrets in containers?',
        ],
        medium: [
            'Design a CI/CD pipeline for a microservices application.',
            'How would you set up disaster recovery for a critical system?',
            'Design an observability stack for a distributed system.',
            'Explain how you would implement infrastructure as code.',
            'How would you handle database migrations in Kubernetes?',
            'Design a multi-environment deployment strategy.',
            'Explain how you would conduct a blameless postmortem.',
            'How would you implement auto-scaling for a stateful service?',
        ],
        hard: [
            'Design a global Kubernetes cluster management strategy.',
            'Explain how you would build a chaos engineering framework.',
            'Design a zero-trust network architecture for Kubernetes.',
            'How would you architect for 99.999% uptime with planned maintenance?',
            'Design a multi-cloud Kubernetes strategy.',
            'Explain how you would implement GitOps at enterprise scale.',
            'Design a cost optimization strategy for large-scale Kubernetes deployments.',
            'How would you build a self-healing infrastructure system?',
        ],
    },
    evaluationCriteria: [
        'Container Orchestration',
        'Infrastructure as Code',
        'Monitoring/Observability',
        'Incident Management',
        'Reliability Engineering',
        'Automation Skills',
    ],
    scoringGuidelines: 'Evaluate based on deep understanding of reliability principles, practical experience with container orchestration, monitoring best practices, incident response skills, and ability to balance reliability with velocity.',
};
