import { DomainPromptConfig } from './base';

export const frontendEngineeringPrompt: DomainPromptConfig = {
    domain: 'Frontend Engineering',
    domainEnum: 'FRONTEND_ENGINEERING',
    persona: {
        en: 'You are a Senior Frontend Architect at a major tech company with 10+ years building web applications used by millions. You are an expert in React, Vue, or Angular, have deep knowledge of browser internals, and have led frontend infrastructure teams. You care deeply about user experience, performance, and accessibility.',
        fr: 'Vous êtes un Architecte Frontend Senior dans une entreprise tech majeure avec plus de 10 ans d\'expérience dans la construction d\'applications web utilisées par des millions d\'utilisateurs. Vous êtes un expert en React, Vue ou Angular, avez une connaissance approfondie des rouages des navigateurs et avez dirigé des équipes d\'infrastructure frontend. Vous vous souciez profondément de l\'expérience utilisateur, de la performance et de l\'accessibilité.',
    },
    subTopics: [
        'JavaScript/TypeScript',
        'React/Vue/Angular',
        'CSS/Styling',
        'State Management',
        'Performance Optimization',
        'Accessibility (a11y)',
        'Testing (Unit/Integration/E2E)',
        'Build Tools',
        'Web APIs',
        'Browser Internals',
        'PWA/Offline',
        'Animation',
    ],
    questionsByLevel: {
        easy: [
            'What is the difference between null and undefined in JavaScript?',
            'Explain how the CSS box model works.',
            'What is the event loop in JavaScript?',
            'How do you center a div in CSS?',
            'What is the difference between let, const, and var?',
            'Explain how responsive design works.',
            'What are semantic HTML elements and why are they important?',
            'How do you handle form validation in frontend?',
        ],
        medium: [
            'Design a state management solution for a complex React application.',
            'How would you optimize the performance of a slow-rendering list?',
            'Design a component library architecture.',
            'Explain how you would implement code splitting in a large application.',
            'How would you handle authentication in a single-page application?',
            'Design an accessible data table component.',
            'Explain how you would implement offline functionality.',
            'How would you set up a testing strategy for a frontend application?',
        ],
        hard: [
            'Design a real-time collaborative editor (like Google Docs).',
            'Explain how you would build a complex animation system.',
            'Design a micro-frontend architecture for a large enterprise application.',
            'How would you implement a virtual DOM from scratch?',
            'Design a state synchronization system for offline-first applications.',
            'Explain how you would build a cross-platform mobile app with web technologies.',
            'Design a performance monitoring system for production web applications.',
            'How would you architect a design system that scales across multiple teams?',
        ],
    },
    evaluationCriteria: [
        'JavaScript Mastery',
        'Framework Knowledge',
        'CSS/Styling Skills',
        'Performance Awareness',
        'Accessibility',
        'Testing Strategy',
    ],
    scoringGuidelines: 'Evaluate based on deep JavaScript understanding, modern framework expertise, performance optimization skills, accessibility awareness, and ability to build scalable frontend systems.',
};
