import { DomainPromptConfig } from './base';

export const mobileDevelopmentPrompt: DomainPromptConfig = {
    domain: 'Mobile Development',
    domainEnum: 'MOBILE_DEVELOPMENT',
    persona: {
        en: 'You are a Lead Mobile Engineer at a top mobile-first company (like Uber, Instagram, or Airbnb) with 10+ years building native and cross-platform mobile applications. You have led teams building apps with 100M+ downloads and have deep expertise in iOS, Android, and React Native. You care about performance, battery life, and delightful user experiences.',
        fr: 'Vous êtes un Lead Ingénieur Mobile dans une entreprise mobile-first de premier plan (comme Uber, Instagram ou Airbnb) avec plus de 10 ans d\'expérience dans la construction d\'applications mobiles natives et cross-platform. Vous avez piloté des équipes construisant des applications avec plus de 100 millions de téléchargements et possédez une expertise approfondie en iOS, Android et React Native. Vous vous souciez de la performance, de la durée de vie de la batterie et d\'expériences utilisateur délicieuses.',
    },
    subTopics: [
        'iOS Development (Swift/SwiftUI)',
        'Android Development (Kotlin/Jetpack)',
        'React Native',
        'Flutter',
        'Mobile Architecture (MVVM/MVI)',
        'App Performance',
        'Push Notifications',
        'Offline Storage',
        'App Security',
        'App Store Deployment',
        'Mobile Testing',
        'Battery Optimization',
    ],
    questionsByLevel: {
        easy: [
            'What is the difference between iOS and Android app development?',
            'Explain the mobile application lifecycle.',
            'What is the purpose of a content provider in Android?',
            'How do you handle network errors in a mobile app?',
            'What is the difference between native and cross-platform development?',
            'Explain how push notifications work.',
            'What is the purpose of dependency injection in mobile apps?',
            'How do you handle offline mode in mobile applications?',
        ],
        medium: [
            'Design an offline-first architecture for a mobile application.',
            'How would you implement deep linking in a mobile app?',
            'Design a caching strategy for a social media mobile app.',
            'Explain how you would optimize app startup time.',
            'How would you implement authentication in a mobile app?',
            'Design a testing strategy for mobile applications.',
            'Explain how you would handle background tasks across iOS and Android.',
            'How would you implement a real-time feature in a mobile app?',
        ],
        hard: [
            'Design a video streaming mobile app with adaptive bitrate.',
            'Explain how you would build a cross-platform framework from scratch.',
            'Design a mobile app architecture supporting multiple device form factors.',
            'How would you implement end-to-end encryption in a messaging app?',
            'Design a mobile CI/CD pipeline with automatic testing on hundreds of devices.',
            'Explain how you would build a AR/VR feature in a mobile app.',
            'Design a memory-efficient image processing pipeline for a photo editing app.',
            'How would you architect a super app with mini-programs?',
        ],
    },
    evaluationCriteria: [
        'Platform Knowledge',
        'Architecture Skills',
        'Performance Optimization',
        'User Experience',
        'Security Awareness',
        'Cross-Platform Thinking',
    ],
    scoringGuidelines: 'Evaluate based on deep platform knowledge, mobile architecture expertise, performance optimization skills, understanding of mobile-specific constraints, and ability to build delightful user experiences.',
};
