import { DomainPromptConfig } from './base';

export const softwareEngineeringPrompt: DomainPromptConfig = {
    domain: 'Software Engineering',
    domainEnum: 'SOFTWARE_ENGINEERING',
    persona: {
        en: 'You are a Principal Software Engineer at a top tech company with 12+ years of experience building large-scale systems. You have led teams of 20+ engineers and have deep expertise in software design patterns, architecture, and development lifecycle. You believe in clean code, testability, and pragmatic solutions.',
        fr: 'Vous êtes un Ingénieur Software Principal dans une entreprise tech de premier plan avec plus de 12 ans d\'expérience dans la construction de systèmes à grande échelle. Vous avez piloté des équipes de plus de 20 ingénieurs et possédez une expertise approfondie en patterns de conception logicielle, architecture et cycle de développement. Vous croyez en un code propre, testable et des solutions pragmatiques.',
    },
    subTopics: [
        'Object-Oriented Design',
        'Design Patterns',
        'SOLID Principles',
        'Clean Architecture',
        'Testing Strategies',
        'Code Review',
        'Refactoring',
        'API Design',
        'Database Design',
        'Concurrency',
        'Memory Management',
        'Performance Optimization',
    ],
    questionsByLevel: {
        easy: [
            'What is the difference between composition and inheritance?',
            'Explain the SOLID principles.',
            'What is the purpose of interfaces in object-oriented programming?',
            'How do you handle errors in your code?',
            'What is the difference between unit testing and integration testing?',
            'Explain the concept of dependency injection.',
            'What is a design pattern? Give an example.',
            'How do you ensure your code is maintainable?',
        ],
        medium: [
            'Design a notification system that supports multiple channels (email, SMS, push).',
            'Explain how you would refactor a 10,000-line legacy module.',
            'Design a rate limiter for an API.',
            'How would you implement an undo/redo feature in a document editor?',
            'Design a logging system for a distributed application.',
            'Explain how you would handle database migrations in a production environment.',
            'Design a configuration management system for a multi-tenant application.',
            'How would you approach designing a real-time collaboration feature?',
        ],
        hard: [
            'Design a payment processing system that handles race conditions and consistency.',
            'Explain how you would architect a system that needs to support 1 million concurrent users.',
            'Design a feature flag system that can be toggled in real-time.',
            'How would you implement a distributed transactions system across multiple services?',
            'Design a code review process that scales across hundreds of engineers.',
            'Explain how you would handle zero-downtime deployments for a critical system.',
            'Design a monitoring and observability system for microservices.',
            'How would you architect a system that requires eventual consistency with strong guarantees?',
        ],
    },
    evaluationCriteria: [
        'Software Design Skills',
        'Code Quality',
        'Testing Approach',
        'Problem Solving',
        'System Thinking',
        'Communication',
    ],
    scoringGuidelines: 'Evaluate based on clarity of thought process, ability to identify trade-offs, code quality awareness, and practical problem-solving approach rather than theoretical answers.',
};
